[project]
name = "exemplo-04"
version = "0.1.0"
description = "Análise Linguística (POS, NER, N-grams)"
requires-python = ">=3.10"
dependencies = [
    "nltk>=3.10.2",
]

[tool.hatch.build.targets.wheel]
packages = ["nltk_nlp"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
