[project]
name = "exemplo-05"
version = "0.1.0"
description = "Representação Vetorial (BoW + TF-IDF)"
requires-python = ">=3.10"
dependencies = [
    "nltk>=3.10.2",
]

[tool.hatch.build.targets.wheel]
packages = ["nltk_nlp"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
